### ISSUE TITLE
[RFE] Add to README the differences between livecd-tools and livemedia-creator tool

### ISSUE THREAD

**Issue by q2dg** [livecd-tools/livecd-tools#111]
I mean...nowadays it seems these two projects overlaps in some ways. 
It seems livemedia-creator is a bit more "official", Anaconda-integrated and complete but I really like the simplicity of livecd-tools. However, I'm talking without any serious information because I can't find any real comparative between these two projects.
What livecd-tools has to offer lorax doesn't? Has livecd-tools a future in a livemedia-creator world?
Thanks a lot

**Comment by hgkamath** [comment]
Of livecd-creator, livecd-iso-todisk, livecd-iso-pxeboot,  the livecd-creator 'may' be eclipsed by livemedia-creator

I found a use case for livecd-iso-to-disk, where in livemedia creator is useful, is first used to create an iso using a 'mock/virtual' environment so that nothing from the build environment goes into the built iso. It also allows options to control the lorax templates. The livecd-iso-to-disk can then be used to unpack the iso onto some partition, with some flexibility as to what goes where. These days one may need to sign one's kernel before burning. Often laptops are shipped to bypass UEFI signature check for optical disk but fail the UEFI check if attempted to do the same with direct to disk image.
 
I don't exactly know how livemedia-creator does this and I could be wrong about this, but RPMS aren't stored as real rpm files. Somehow get rpms are installed from installed packages on the sqaushfs onto the host machine. as OP indicated may have something to do with anaconda integration.  

so may be livemedia-creator is good for building an iso
and livecd-iso-to-disk is presently good to flexibly get the iso onto any medium.

Unless the same kinds of controls like, bootloader, efi,  destination  are already there in livemedia-creator. It may be that I did not explore livemediacreator enough, and chose livecd-tools out of familiarity.

**Comment by FGrose** [comment]
I'll highlight 3 tools unique to _**livecd-tools**_:

- _**livecd-iso-to-disk**_  -- loads a liveCD onto USB media with options for persistent overlays
- _**liveimage-mount**_  -- mounts a liveCD/USB in order to examine the embedded filesystem or even edit one with a persistent overlay
- _**editliveos**_ -- edit a liveOS to merge persistent overlay, adjust filesystem sizes or types, include or exlude files, rebuild a new .iso, and refresh the persistent overlay.

See 581f5cd781798f0f159e9e900cad92d895e7da31 for a README patch.

Conan-Kudo can compare _lorax_ and _livemedia-creator_ to _imgcreate_ and _livecd-create_.

**Comment by q2dg** [comment]
Thanks! I'll close the issue, if you don't mind
